apiVersion: v1
kind: Service
metadata:
  name: travelstory-service
  namespace: 2401198
spec:
  selector:
    app: travelstory
  ports:
    - name: frontend
      port: 80
      targetPort: 80
    - name: backend
      port: 5000
      targetPort: 5000
  type: LoadBalancer
